version: "3.4"

services:

  base:
    build:
      context: ./base/$OSNAME
      network: ${DOCKER_BUILD_NETWORK:-bridge}
      args:
          - INDY_SDK_VERSION
          - u_id=${DOCKER_UID}
    image: ${LST_BASE_DOCKER_NAME}:${LST_BASE_DOCKER_TAG}

  ci:
    build:
      context: ./ci/$OSNAME
      network: ${DOCKER_BUILD_NETWORK:-bridge}
    image: ${LST_CI_DOCKER_NAME}:${LST_CI_DOCKER_TAG}
