[package]
name = "create_payment_demo"
version = "0.1.0"
authors = ["matt raffel <matt.raffel@evernym.com>"]
build = "build.rs"

[dependencies]
ansi_term = "0.11.0"
lazy_static = "0.2"
libc = "0.2.21"