[package]
name = "libsovtoken"
version = "0.1.0"
authors = [
  "Matt Raffel <matt.raffel@evernym.com",
  "Stephen Felt <stephen.felt@evernym.com"
  ]

description = "Payment handler for Sovrin tokens in libindy"


[dependencies]
libc = "0.2.21"
indy = { git = "https://github.com/hyperledger/indy-sdk.git" }


[lib]
name = "sovtoken"
path = "src/lib.rs"
crate-type = ["dylib"]
